% Auto-generated by cameraCalibrator app on 09-Dec-2014
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker2.jpg',...
    'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker4.jpg',...
    'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker6.jpg',...
    'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker7.jpg',...
    'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker8.jpg',...
    'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker12.jpg',...
    'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker13.jpg',...
    'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker16.jpg',...
    'C:\Program Files\MATLAB\R2014b\toolbox\vision\visiondemos\calibration\slr\Checker17.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 3.250000e+01;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm');

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('SparseReconstructionExample')
